# Règle par défaut
test:
	g++ -std=c++23 -Wall -Wextra -pedantic main.cpp matricule.cpp memory.cpp -o matricule		
	python3 tests1.py ./matricule
	python3 tests2.py ./matricule
	python3 tests3.py ./matricule
